name: Nodejs-CI

on: workflow_dispatch

jobs:
  builds-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: install dependancies
        run: |
          npm install
          npm test

      - name: Run tests
        run: |
         mkdir -p reports
         npm test
         
      - name: upload test as artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: test-logs
          path: reports/
      
